config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :admin_users, ActiveAdmin::Devise.config.merge({
    controllers: ActiveAdmin::Devise.controllers.merge(invitations: "admin/invitations")
  })

  ActiveAdmin.routes(self)

  root "pages#home"

  get "/admin_users" => "admin/dashboard#index", as: :admin_user_root

  resources :archives, only: %i[index show]
  resources :books, only: %i[index show]
  resources :educations, only: %i[index show]
  resources :iconographies, only: %i[index show]
  resources :newspapers, only: %i[index show]
  resources :saviors, only: %i[index show]
  resources :survivors, only: %i[index show]
end

app/views/shared/_footer.html.erb
<footer class="main-page-footer">
  <div class="footer-logo">
    <%= link_to("https://www.arqshoah.com/", { target: "_blank", rel: :noopener }) do %>
      <%= image_tag("arqshoah-logo-transparent.png", alt: "Arqshoah logo") %>
    <% end %>
  </div>
  <div class="footer-copyright">
    © 2022 Copyright - Arqshoah / LEER. FFLCH/USP
  </div>
  <div class="footer-contacts">
    +55 11 3091 8598 | <%= mail_to("leer@usp.br", subject: "Contacto Arqshoah Arquivo Virtual") %>
  </div>
</footer>

app/views/shared/_index_page_header.html.erb
<div class="row mb-3">
  <div class="col-12 col-md-10">
    <h1 class="text-center"><%= local_assigns.fetch(:title, records.model_name.human(count: 2)) %></h1>
  </div>
  <div class="col-12 col-md-2">
    <div class="float-end">
      <%= button_tag(class: "btn btn-primary ", type: "button", data: { "bs-toggle": "offcanvas", "bs-target": "#offcanvas-search-form" }, aria: { controls: "offcanvas-search-form" }) do %>
        <i class="fas fa-search"></i>
      <% end %>
      <% if admin_user_signed_in? %>
        <%= link_to([:new, :admin, records.model_name.singular_route_key.to_sym], class: "btn btn-primary") do %>
          <i class="fas fa-plus-square"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<%= paginate records, window: 1 %>

<%= render "shared/search_form_offcanvas", q: @q %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to(root_path, class: "navbar-brand") do %>
      <%= image_tag("favicon.ico", width: "24", height: "24") %> Arqshoah
    <% end %>

    <%= button_tag(sanitize("<span class='navbar-toggler-icon'></span>", { tags: %w[span] }), { class: "navbar-toggler", type: "button", data: { "bs-toggle" => "collapse", "bs-target" => "#main-navbar" }, aria: { controls: "main-navbar", expanded: "false", label: "Toggle navigation" } }) %>

    <div class="collapse navbar-collapse" id="main-navbar">
      <div class="navbar-nav w-100">
        <%= link_to(Archive.model_name.human(count: 2), archives_path, { class: "nav-link#{' active' if request.filtered_parameters[:controller] == 'archives'}", aria: { current: request.filtered_parameters[:controller] == "archives" ? "active" : nil } }) %>
        <%= link_to(I18n.t(:collection, scope: [Book.i18n_scope, :models, Book.model_name.i18n_key]), books_path, { class: "nav-link#{' active' if request.filtered_parameters[:controller] == 'books'}", aria: { current: request.filtered_parameters[:controller] == "books" ? "active" : nil } }) %>
        <%= link_to(Education.model_name.human(count: 2), educations_path, { class: "nav-link#{' active' if request.filtered_parameters[:controller] == 'educations'}", aria: { current: request.filtered_parameters[:controller] == "educations" ? "active" : nil } }) %>
        <%= link_to(I18n.t(:collection, scope: [Newspaper.i18n_scope, :models, Newspaper.model_name.i18n_key]), newspapers_path, { class: "nav-link#{' active' if request.filtered_parameters[:controller] == 'newspapers'}", aria: { current: request.filtered_parameters[:controller] == "newspapers" ? "active" : nil } }) %>
        <%= link_to(Iconography.model_name.human(count: 2), iconographies_path, { class: "nav-link#{' active' if request.filtered_parameters[:controller] == 'iconographies'}", aria: { current: request.filtered_parameters[:controller] == "iconographies" ? "active" : nil } }) %>
        <%= link_to(Savior.model_name.human(count: 2), saviors_path, { class: "nav-link#{' active' if request.filtered_parameters[:controller] == 'saviors'}", aria: { current: request.filtered_parameters[:controller] == "saviors" ? "active" : nil } }) %>
        <%= link_to(Survivor.model_name.human(count: 2), survivors_path, { class: "nav-link#{' active' if request.filtered_parameters[:controller] == 'survivors'}", aria: { current: request.filtered_parameters[:controller] == "survivors" ? "active" : nil } }) %>

        <% if admin_user_signed_in? %>
          <div class="nav-item dropdown ms-auto">
            <%= link_to(current_admin_user.email, nil, { class: "nav-link dropdown-toggle", id: "main-navbar-dropdown", role: "button", data: { "bs-toggle" => "dropdown" }, aria: { expanded: "false" } }) %>
            <div class="dropdown-menu" aria-labelledby="main-navbar-dropdown">
              <%= link_to("Admin", admin_root_path, class: "dropdown-item") %>
              <%= link_to("Logout", destroy_admin_user_session_path, method: :delete, class: "dropdown-item") %>
            </div>
          </div>
        <% else %>
          <%= link_to("Login", new_admin_user_session_path, class: "nav-link active ms-auto") %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_record_card.html.erb
<div class="col">
  <div class="card h-100 border-primary shadow-lg" style="max-width: 500px;">
    <%= link_to(record, class: "btn btn-primary btn-sm position-absolute top-0 end-0") do %>
      <i class="fas fa-eye"></i>
    <% end %>
    <% if admin_user_signed_in? %>
      <%= link_to([:edit, :admin, record], class: "btn btn-primary btn-sm position-absolute bottom-0 end-0") do %>
        <i class="fas fa-edit"></i>
      <% end %>
    <% end %>

    <div class="row g-0">
      <div class="col-md-4">
        <% if record.respond_to?(:images) && record.images.attached? %>
          <div id="index-page-carousel" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
              <% record.images.each_with_index do |image, index| %>
                <div class="carousel-item <%= "active" if index.zero? %>">
                  <%= image_tag(image.variant({ resize_to_fill: [250, 325, { crop: :attention }] }), { class: "img-fluid rounded-start mx-auto d-block" }) %>
                </div>
              <% end %>
            </div>
          </div>
        <% elsif record.respond_to?(:image) && record.image.attached? %>
          <%= image_tag(record.image.variant({ resize_to_fill: [250, 325, { crop: :attention }] }), { class: "img-fluid rounded-start mx-auto d-block" }) %>
        <% else %>
          <%= image_tag("image-placeholder.png", class: "img-fluid rounded-start mx-auto d-block", style: "max-height: 200px") %>
        <% end %>
      </div>

      <div class="col-md-8 d-flex flex-column">
        <div class="card-body">
          <h5 class="card-title text-truncate"><%= record.try(:title) || record.try(:name) %></h5>
          <p class="card-text text-truncate"><%= record.registration %></p>
          <p class="card-text text-truncate">
            <%= record.try(info_one).try(:name) || record.try(info_one) %>
            <br>
            <%= record.try(info_two).try(:name) || record.try(info_two) %>
          </p>
        </div>
        <div class="card-footer align-bottom"><small class="text-muted">Atualizado<%= time_ago_in_words(record.updated_at) %></small></div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_search_form_offcanvas.html.erb
<div class="offcanvas offcanvas-start" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvas-search-form" aria-labelledby="offcanvas-search-form">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvas-search-form"><%= t("ransack.search").capitalize %></h5>
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <%= render "search_form", q: @q %>
  </div>
</div>

app/views/shared/_show_page_carousel.html.erb
<% if record.respond_to?(:images) && record.images.attached? %>
  <div id="show-page-carousel" class="carousel carousel-dark slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <% record.images.with_all_variant_records.each_with_index do |image, index| %>
        <div class="carousel-item <%= "active" if index.zero? %>">
          <%= link_to(rails_blob_path(image, disposition: "inline"), target: :_blank, rel: :noopener) do %>
            <%= image_tag(image.variant(resize_to_fit: [nil, 530]), class: "d-block img-fluid mx-auto") %>
          <% end %>
        </div>
      <% end %>
      <button class="carousel-control-prev" type="button" data-bs-target="#show-page-carousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Anterior</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#show-page-carousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Seguinte</span>
      </button>
    </div>
  </div>
<% elsif record.respond_to?(:image) && record.image.attached? %>
  <%= link_to(rails_blob_path(record.image, disposition: "inline"), target: :_blank, rel: :noopener) do %>
    <%= image_tag(record.image.variant(resize_to_fit: [nil, 530]), class: "d-block img-fluid mx-auto") %>
  <% end %>
<% else %>
  <%= image_tag("arqshoah-logo.png", class: "d-block img-fluid mx-auto") %>
<% end %>

app/views/shared/_show_page_header.html.erb
<div class="row">
  <div class="col-11">
    <h1 class="text-center"><%= record.try(:title) || record.try(:name) %></h1>
    <% if record.try(:subtitle) %>
      <h2 class="text-center"><%= record.try(:subtitle) %></h2>
    <% end %>
  </div>

  <% if admin_user_signed_in? %>
    <div class="col-1">
      <%= link_to([:edit, :admin, record], class: "btn btn-primary float-end") do %>
        <i class="fas fa-edit"></i>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_show_page_pdf.html.erb
<% if record.respond_to?(:pdf) && record.pdf.attached? %>
  <tr>
    <th scope="row"><%= record.class.human_attribute_name(:pdf) %></th>
    <td>
      <%= link_to(rails_blob_path(record.pdf, disposition: "inline"), target: :_blank, rel: :noopener) do %>
        <%= render("active_storage/blobs/blob", blob: record.pdf, size: [75, 100]) %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/shared/_show_page_table.html.erb
<table class="table table-hover">
  <tbody>
    <% record.class::DETAIL_ATTRIBUTES.each do |att| %>
      <% if record.try(att[:attribute]) %>
        <% if att[:type] == :direct %>
          <tr>
            <th scope="row"><%= record.class.human_attribute_name(att[:attribute]) %></th>
            <td><%= record.try(att[:attribute]) %></td>
          </tr>
        <% elsif att[:type] == :date_display %>
          <tr>
            <th scope="row"><%= record.class.human_attribute_name(att[:attribute]) %></th>
            <td><%= record.date_display(att[:attribute]) %></td>
          </tr>
        <% elsif att[:type] == :associated %>
          <tr>
            <th scope="row"><%= record.class.human_attribute_name(att[:attribute]) %></th>
            <td><%= record.try(att[:attribute]).try(:name) %></td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
    <%= render "shared/show_page_pdf", { record: record } %>
  </tbody>
</table>