config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  devise_for :admin_users, ActiveAdmin::Devise.config.merge({
    controllers: ActiveAdmin::Devise.controllers.merge(invitations: "admin/invitations")
  })

  ActiveAdmin.routes(self)

  root "pages#home"

  get "/admin_users" => "admin/dashboard#index", as: :admin_user_root

  resources :archives, only: %i[index show]
  resources :books, only: %i[index show]
  resources :educations, only: %i[index show]
  resources :iconographies, only: %i[index show]
  resources :newspapers, only: %i[index show]
  resources :saviors, only: %i[index show]
  resources :survivors, only: %i[index show]
end

app/views/shared/accordion_items/_citations.html.erb
<% if record.people_cited.present? %>
  <div class="accordion-item">
    <h2 class="accordion-header" id="citations-panel">
      <%= button_tag(class: "accordion-button collapsed", type: "button", data: { "bs-toggle": "collapse", "bs-target": "#citations-panel-collapse" }, aria: { expanded: false, controls: "citations-panel-collapse" }) do %>
        <%= record.class.human_attribute_name(:people_cited) %>
      <% end %>
    </h2>
    <div id="citations-panel-collapse" class="accordion-collapse collapse" aria-labelledby="citations-panel">
      <div class="accordion-body">
        <div class="row">
          <% if record.survivors_citations.present? %>
            <div class="col-12 col-lg-4">
              <p><strong><%= Survivor.model_name.human(count: 2) %></strong></p>
              <div class="list-group">
                <% record.survivors_citations.each do |survivor| %>
                  <%= link_to(survivor.name, survivor_path(survivor), class: "list-group-item list-group-item-action") %>
                <% end %>
              </div>
            </div>
          <% end %>
          <% if record.savior_citations.present? %>
            <div class="col-12 col-lg-4">
              <p><strong><%= Savior.model_name.human(count: 2) %></strong></p>
              <div class="list-group">
                <% record.savior_citations.each do |savior| %>
                  <%= link_to(savior.name, savior_path(savior), class: "list-group-item list-group-item-action") %>
                <% end %>
              </div>
            </div>
          <% end %>
          <% if record.commoners_citations.present? %>
            <div class="col-12 col-lg-4">
              <p><strong><%= Commoner.model_name.human(count: 2) %></strong></p>
              <ul class="list-group">
                <% record.commoners_citations.each do |commoner| %>
                  <li class="list-group-item"><%= commoner.name %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/accordion_items/_professional_activities.html.erb
<% if record.academic_formation.present? || record.professional_activities.present? %>
  <div class="accordion-item">
    <h2 class="accordion-header" id="professional-activities-panel">
      <%= button_tag({ class: "accordion-button collapsed", type: "button", data: { "bs-toggle": "collapse", "bs-target": "#professional-activities-panel-collapse" }, aria: { expanded: false, controls: "professional-activities-panel-collapse" } }) do %>
        <%= record.class.human_attribute_name(:professional_activities) %>
      <% end %>
    </h2>
    <div id="professional-activities-panel-collapse" class="accordion-collapse collapse" aria-labelledby="professional-activities-panel">
      <div class="accordion-body">
        <p><strong><%= record.class.human_attribute_name(:academic_formation) %></strong>: <%= record.academic_formation %></p>
        <%= record.professional_activities %>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/accordion_items/_rich_text.html.erb
<% if record.try(rich_text_name) %>
  <div class="accordion-item">
    <h2 class="accordion-header" id="<%= "#{rich_text_name}-panel-heading" %>">
      <%= button_tag(class: "accordion-button collapsed", type: "button", data: { "bs-toggle": "collapse", "bs-target": "##{rich_text_name}-panel-collapse" }, aria: { expanded: false, controls: "#{rich_text_name}-panel-collapse" }) do %>
        <%= record.class.human_attribute_name(rich_text_name) %>
      <% end %>
    </h2>
    <div id="<%= "#{rich_text_name}-panel-collapse" %>" class="accordion-collapse collapse" aria-labelledby="<%= "#{rich_text_name}-panel-heading" %>">
      <div class="accordion-body">
        <%= record.try(rich_text_name) %>
      </div>
    </div>
  </div>
<% end %>